### ISSUE TITLE
Getting error when using FT SDK in Android app

### ISSUE THREAD

**Issue by ram1972** [FeitianSmartcardReader/FEITIAN_MOBILE_READERS#35]
I am getting following error in the app. It is coming during initial loading:

Line causing error:
             **mFTReader = new FTReader(activity, mHandler, DK.FTREADER_TYPE_BT4);**
Error:
**java.lang.UnsatisfiedLinkError: dlopen failed: library "libFTReaderPCSC_1.0.8.so" not found**
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.ftsafe.ftnative.FTNative.<clinit>(FTNative.java:8)
        at com.ftsafe.ftnative.FTNative.init(Native Method)
        at com.ftsafe.comm.CommBase.<init>(CommBase.java:42)
        at com.ftsafe.readerScheme.FTReader.<init>(FTReader.java:21)
        at com.Modules.UnassistedA.UnassistedSettingsDialog.onClick(UnassistedSettingsDialog.java:529)
        at android.view.View.performClick(View.java:8160)
        at android.widget.TextView.performClick(TextView.java:16234)
        at android.view.View.performClickInternal(View.java:8137)
        at android.view.View.access$3700(View.java:888)
        at android.view.View$PerformClick.run(View.java:30242)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:247)
        at android.app.ActivityThread.main(ActivityThread.java:8676)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by FeitianSmartcardReader** [comment]
@ram1972 please download below library and using the latest SDK. the error shows cannot find this lib, please double check you have libFTReaderPCSC_1.0.8.so in our SDK folder. thanks 
https://github.com/FeitianSmartcardReader/FEITIAN_MOBILE_READERS/files/8241680/CardReader_1.0.9.5.zip
